export const HARDCODED_WORKOUTS = [
  {
    dayOfWeek: 0,
    dayName: "Monday",
    workoutType: "Upper Strength",
    exercises: [
      { name: "Barbell Bench Press", setsTarget: 5, repsTarget: "5" },
      { name: "Pull-ups / Lat Pulldown", setsTarget: 4, repsTarget: "6-10" },
      { name: "Incline Dumbbell Press", setsTarget: 4, repsTarget: "8" },
      { name: "Barbell Row", setsTarget: 4, repsTarget: "6-8" },
      { name: "Cable Fly", setsTarget: 3, repsTarget: "12-15" },
      { name: "Rope Pushdown", setsTarget: 3, repsTarget: "12-15" },
    ],
  },
  {
    dayOfWeek: 1,
    dayName: "Tuesday",
    workoutType: "Lower Strength + Core",
    exercises: [
      { name: "Back Squat", setsTarget: 5, repsTarget: "5" },
      { name: "Romanian Deadlift", setsTarget: 4, repsTarget: "8" },
      { name: "Leg Press", setsTarget: 3, repsTarget: "10-12" },
      { name: "Walking Lunges", setsTarget: 2, repsTarget: "20 steps" },
      { name: "Standing Calf Raises", setsTarget: 4, repsTarget: "15" },
      { name: "Hanging Leg Raises", setsTarget: 3, repsTarget: "10-12" },
      { name: "Cable Crunch", setsTarget: 3, repsTarget: "12-15" },
    ],
  },
  {
    dayOfWeek: 2,
    dayName: "Wednesday",
    workoutType: "Rest",
    exercises: [
      { name: "Walking (20-30 min)", setsTarget: 1, repsTarget: "light" },
      { name: "Mobility - Shoulders", setsTarget: 1, repsTarget: "5 min" },
      { name: "Mobility - Hips", setsTarget: 1, repsTarget: "5 min" },
      { name: "Mobility - Hamstrings", setsTarget: 1, repsTarget: "5 min" },
    ],
  },
  {
    dayOfWeek: 3,
    dayName: "Thursday",
    workoutType: "Push Hypertrophy",
    exercises: [
      { name: "Incline Barbell Bench", setsTarget: 4, repsTarget: "6-8" },
      { name: "Flat Dumbbell Press", setsTarget: 4, repsTarget: "8-10" },
      { name: "Weighted Dips", setsTarget: 3, repsTarget: "8-12" },
      { name: "Dumbbell Lateral Raises", setsTarget: 5, repsTarget: "12-15" },
      { name: "Rear Delt Fly", setsTarget: 3, repsTarget: "15" },
      { name: "Overhead Tricep Extension", setsTarget: 3, repsTarget: "12" },
      { name: "Rope Pushdown", setsTarget: 2, repsTarget: "15" },
    ],
  },
  {
    dayOfWeek: 4,
    dayName: "Friday",
    workoutType: "Pull Hypertrophy",
    exercises: [
      { name: "Deadlift (technique)", setsTarget: 4, repsTarget: "4" },
      { name: "Seated Cable Row", setsTarget: 4, repsTarget: "8-12" },
      { name: "Lat Pulldown (wide)", setsTarget: 4, repsTarget: "10" },
      { name: "Face Pulls", setsTarget: 3, repsTarget: "15" },
      { name: "EZ Bar Curl", setsTarget: 3, repsTarget: "8-10" },
      { name: "Hammer Curl", setsTarget: 3, repsTarget: "12" },
    ],
  },
  {
    dayOfWeek: 5,
    dayName: "Saturday",
    workoutType: "Arms + Conditioning",
    exercises: [
      { name: "Close Grip Bench", setsTarget: 4, repsTarget: "6-8" },
      { name: "Incline DB Curl", setsTarget: 4, repsTarget: "10" },
      { name: "Cable Tricep Pushdown", setsTarget: 3, repsTarget: "12" },
      { name: "Preacher / Machine Curl", setsTarget: 3, repsTarget: "12" },
      { name: "Cable Fly", setsTarget: 3, repsTarget: "15" },
      { name: "Lateral Raises", setsTarget: 3, repsTarget: "15" },
    ],
  },
  {
    dayOfWeek: 6,
    dayName: "Sunday",
    workoutType: "Full Rest",
    exercises: [
      { name: "Recovery & Stretching", setsTarget: 1, repsTarget: "light" },
      { name: "Hydration Check", setsTarget: 1, repsTarget: "all day" },
    ],
  },
]
